### ISSUE TITLE
gpio mmap error

### ISSUE THREAD

**Issue by mattb1969** [BostinTechnology/RadarPi#1]
Error message when happens in data timer, ONLY whilst in ADC mode.

bcm2835_init: gpio mmap failed: Cannot allocate memory
bcm2835_init failed. Are you running as root?

**Comment by mattb1969** [comment]
I wonder if this error is related to the setup of the SPI ports and not due to something I’ve coded.
However, I have changed it now that it only does GPIO setup when that mode is selected and not continually.

**Comment by mattb1969** [comment]
I have noticed that this error only occurs in some situations. Trying different combinations of button pressing can make it occur, but at present, I have not been able to find the combination that shows the error.

**Comment by ITSparkles** [comment]
Dont see this behaviour in the updated version that fixes the way the SPI ports are accessed.
