### ISSUE TITLE
Test Program - Range Test

### ISSUE THREAD

**Issue by DuncanBennett2** [BostinTechnology/RadarPi#32]
Run test program. When selecting Range Test (r) from menu the response is "Unable to control LEDs. test aborted"

**Comment by mattb1969** [comment]
Error occurs when setting up the LEDs, this could be due to sudo or maybe gpis setup is incorrect

**Comment by mattb1969** [comment]
Fixed issues with range test.
Unable to control LEDs was caused by me looking for a pass, but the coder returned zero as a pass instead.
Also fixed the LEDs so they now flash accordingly.
