### ISSUE TITLE
radarVisual execution

### ISSUE THREAD

**Issue by DuncanBennett2** [BostinTechnology/RadarPi#33]
When typing sudo ./radarVisual I get-
** (radarVisual:8291): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
Unable to read file: ../Visual/gui/main_window.glade: required gtk+ version 3.20, current version is 3.14

**Comment by mattb1969** [comment]
Incorrect version of software - this is now resolved with the setup script that has been created.
