### ISSUE TITLE
Initialisation of buses incorrectly repeated causing delays

### ISSUE THREAD

**Issue by mattb1969** [BostinTechnology/RadarPi#4]
In data timer, it is continually refreshing the spi and gpio stuff. This should be done once only
 
Consider moving it to the area when you choose mode, not get data...
Be careful of the gain, this is a different SPI channel.

**Comment by mattb1969** [comment]
There is a function for Start / Stop. This should be where I initialise and kill the ports.
Updated the data capture routine to only capture data when it is running, it will reinitialise the list if it is not running and the list hasn’t been reinitialised.
Updated screen refresh timer to only run when the data capture is running

**Comment by mattb1969** [comment]
Functionality has now been incorporated into Start / Stop.

**Comment by mattb1969** [comment]
Please retest and close if working ok.

**Comment by mattb1969** [comment]
A new version has been pushed to GitHub, please download and retest.

**Comment by ITSparkles** [comment]
appears to be working at the intended speed of data collection.
