### ISSUE TITLE
radarVisual - something wrong with the data

### ISSUE THREAD

**Issue by ITSparkles** [BostinTechnology/RadarPi#7]
Previous data points are being rewritten from the value they first appeared with.

Try running any of the modes and watch the most recent data point poduced as it is replaced with more recent ones.

**Comment by mattb1969** [comment]
New readings are added to the head of the list1, so the oldest value is always the tail, which is listed last. The reasoning for the logic is that means the last point drawn on the graph is the oldest value as it draws left to right.
Can we discuss tomorrow.

**Comment by mattb1969** [comment]
Are you happy for us to close this one, or do you think there still needs to be improvements with the messaging on the debug window?

**Comment by mattb1969** [comment]
I have changed the debug messaging so it only shows the latest 5 readings, not all of them.
